### ISSUE TITLE
'OPENCV_IO_ENABLE_OPENEXR' 　error

### ISSUE THREAD

**Issue by Arakawa-Youhei** [wutong16/HyperDreamer#10]
I run
Stage2 DMTet　

This is error.

cv2.error: OpenCV(4.10.0) /io/opencv/modules/imgcodecs/src/grfmt_exr.cpp:103: error: (-213:The function/feature is not implemented) imgcodecs: OpenEXR codec is disabled. You can enable it via 'OPENCV_IO_ENABLE_OPENEXR' option. Refer for details and cautions here: https://github.com/opencv/opencv/issues/21326 in function 'initOpenEXR'

What should I do ?

I hope this solves the problem.

**Comment by Lizb6626** [comment]
Before `import cv2`, set `os.environ["OPENCV_IO_ENABLE_OPENEXR"] = "1"`. Then, you can read the .exr image using `cv2.imread(IMG_PATH, cv2.IMREAD_UNCHANGED)` .

Are you working with `.exr` images? Currently, we only support 8-bit images as input. You may need to implement additional code to convert the `.exr` image into the `[0, 1]` range, as .exr images are not in the `[0, 255]` range like 8-bit PNG images.

**Comment by Arakawa-Youhei** [comment]
Thank you! The issue has been resolved!
