### ISSUE TITLE
Image preprocessing error

### ISSUE THREAD

**Issue by jly0810** [wutong16/HyperDreamer#3]
How can I solve the following error while performing image preprocessing?

![image](https://github.com/wutong16/HyperDreamer/assets/89561918/0d1c3714-3678-41e4-a6df-9eefbea2e29c)

**Comment by Lizb6626** [comment]
Could you provide more detailed info? Like the version of openclip. It seems a bug when calling openclip.

**Comment by jly0810** [comment]
In /HyperDreamer/lib/python3.10/site-packages/open_clip/coca_model.py", line 442 change to：  if beam_scorer.is_done or all(stopping_criteria(input_ids, None))
The above method can solve the problem.
