### ISSUE TITLE
TypeError: Trainer.load_envmap() 

### ISSUE THREAD

**Issue by Arakawa-Youhei** [wutong16/HyperDreamer#6]
Hi @Lizb6626 

I run 
`bash run_dmtet.sh '/data/strawberry_rgba.png' '/exp/strawberry_s1' '/exp/strawberry_s2' --test --relight_sg envmaps/lgtSGs_studio.npy
`

"main.py", line 342, in <module>
    trainer.load_envmap()
TypeError: Trainer.load_envmap() missing 1 required positional argument: 'envmap'

What shuld I do ?

**Comment by Lizb6626** [comment]
Thank you for bringing this to our attention. 
The bug has been resolved (https://github.com/wutong16/HyperDreamer/blob/master/main.py#L342). Please update to the latest version.

**Comment by Arakawa-Youhei** [comment]
Thank you for answering my question.
`TypeError: Trainer.load_envmap() missing 1 required positional argument: 'envmap` is gone.
But new error has appeared.

>==> Relighting: load light from envmaps/lgtSGs_studio.npy
Traceback (most recent call last):
  File "/home/arakawa/HyperDreamer/main.py", line 342, in <module>
    trainer.load_envmap(opt.relight_sg)
  File "/home/arakawa/HyperDreamer/nerf/utils.py", line 1672, in load_envmap
    self.model.load_envmap(envmap)
  File "/home/arakawa/HyperDreamer/nerf/network_grid.py", line 388, in load_envmap
    self.lgtSGs.load_light(envmap)
  File "/home/arakawa/HyperDreamer/nerf/network_grid.py", line 107, in load_light
    self.lgtSGs = nn.Parameter(torch.from_numpy(envmap).to(device), requires_grad=True)
                               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected np.ndarray (got str)

**Comment by Lizb6626** [comment]
Please update to the latest version.

**Comment by Arakawa-Youhei** [comment]
Thank you! The issue has been resolved!
